-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 06:09:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_green_advisor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `my_green_advisor` ;

-- -----------------------------------------------------
-- Schema my_green_advisor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_green_advisor` DEFAULT CHARACTER SET utf8 ;
USE `my_green_advisor` ;

-- -----------------------------------------------------
-- Table `my_green_advisor`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`Events` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`Events` (
  `idEvents` INT NOT NULL AUTO_INCREMENT,
  `name_events` VARCHAR(45) NULL,
  `content_event` VARCHAR(45) NULL,
  `users_has_favorite_users_idusers` VARCHAR(40) NOT NULL,
  `users_has_favorite_favorite_idfavorite_places` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEvents`, `users_has_favorite_users_idusers`, `users_has_favorite_favorite_idfavorite_places`),
  INDEX `fk_Events_users_has_favorite1_idx` (`users_has_favorite_users_idusers` ASC, `users_has_favorite_favorite_idfavorite_places` ASC) VISIBLE,
  CONSTRAINT `fk_Events_users_has_favorite1`
    FOREIGN KEY (`users_has_favorite_users_idusers` , `users_has_favorite_favorite_idfavorite_places`)
    REFERENCES `my_green_advisor`.`users_has_favorite` (`users_idusers` , `favorite_idfavorite_places`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_green_advisor`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`favorite` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`favorite` (
  `idfavorite_places` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `gps_position` VARCHAR(45) NULL,
  PRIMARY KEY (`idfavorite_places`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_green_advisor`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`users` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`users` (
  `idusers` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_green_advisor`.`users_has_favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`users_has_favorite` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`users_has_favorite` (
  `users_idusers` VARCHAR(40) NOT NULL,
  `favorite_idfavorite_places` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_idusers`, `favorite_idfavorite_places`),
  INDEX `fk_users_has_favorite_favorite1_idx` (`favorite_idfavorite_places` ASC) VISIBLE,
  INDEX `fk_users_has_favorite_users_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_favorite_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `my_green_advisor`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_favorite_favorite1`
    FOREIGN KEY (`favorite_idfavorite_places`)
    REFERENCES `my_green_advisor`.`favorite` (`idfavorite_places`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
