-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 22:35:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_green_advisor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `my_green_advisor` ;

-- -----------------------------------------------------
-- Schema my_green_advisor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_green_advisor` DEFAULT CHARACTER SET utf8 ;
USE `my_green_advisor` ;

-- -----------------------------------------------------
-- Table `my_green_advisor`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`Events` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`Events` (
  `idEvents` INT NOT NULL,
  `name_events` VARCHAR(45) NULL,
  `content_event` VARCHAR(45) NULL,
  `favorite_has_users_favorite_places_idfavorite_places` INT NOT NULL,
  `favorite_has_users_users_idusers` INT NOT NULL,
  PRIMARY KEY (`idEvents`, `favorite_has_users_favorite_places_idfavorite_places`, `favorite_has_users_users_idusers`),
  INDEX `fk_Events_favorite_has_users1_idx` (`favorite_has_users_favorite_places_idfavorite_places` ASC, `favorite_has_users_users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_Events_favorite_has_users1`
    FOREIGN KEY (`favorite_has_users_favorite_places_idfavorite_places` , `favorite_has_users_users_idusers`)
    REFERENCES `my_green_advisor`.`favorite_has_users` (`favorite_places_idfavorite_places` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_green_advisor`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`favorite` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`favorite` (
  `idfavorite_places` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `gps_position` VARCHAR(45) NULL,
  PRIMARY KEY (`idfavorite_places`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usersmy_green_advisor`.`favorite_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`favorite_has_users` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`favorite_has_users` (
  `favorite_places_idfavorite_places` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`favorite_places_idfavorite_places`, `users_idusers`),
  INDEX `fk_favorite_places_has_users_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_favorite_places_has_users_favorite_places_idx` (`favorite_places_idfavorite_places` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_places_has_users_favorite_places`
    FOREIGN KEY (`favorite_places_idfavorite_places`)
    REFERENCES `my_green_advisor`.`favorite` (`idfavorite_places`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_places_has_users_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `my_green_advisor`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_green_advisor`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_green_advisor`.`users` ;

CREATE TABLE IF NOT EXISTS `my_green_advisor`.`users` (
  `idusers` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
